import { CivicReport } from "./types.ts";
import { generateDeterministicSemanticVector } from "./geo.ts";

export const INITIAL_SEED_REPORTS: CivicReport[] = [
  // --- HYDERABAD, INDIA: 7 CITIZEN REPORTS CORROBORATED INTO 1 SINGLE PROBLEM ---
  {
    id: "rep-000-flood",
    referenceId: "BRICS-IND-2026-7707",
    ticketId: "CYP-2026-7707",
    timestamp: "2026-08-19 14:32 UTC",
    createdAt: Date.now() - 1000 * 60 * 12,
    citizenName: "Ramesh Sharma (+6 other citizens)",
    verifiedPhone: "+91 98490 12345",
    country: "India",
    language: "Telugu / Hindi / English (Merged)",
    documentType: "Aadhaar Card",
    problemDomain: "Water",
    location: "Cyber Towers Storm Culvert & Feeder Substation, Hitec City, Hyderabad",
    lat: 17.4474,
    lng: 78.3762,
    coordinates: { lat: 17.4474, lng: 78.3762 },
    typedComplaint: "Heavy monsoon cloudburst ruptured stormwater barrier. 7 citizen calls logged across 85m radius. Water level at 4.2 feet threatening electrical transformer.",
    hasAudio: true,
    hasPhoto: true,
    preRepairPhotoUrl: "https://images.unsplash.com/photo-1547683905-f686c993aae5?w=800&auto=format&fit=crop&q=80",
    postRepairPhotoUrl: "https://images.unsplash.com/photo-1584467735815-f778f274e296?w=800&auto=format&fit=crop&q=80",
    transcription: "వరద నీరు ట్రాన్స్‌ఫార్మర్ దగ్గరకు వచ్చేసింది, 7 మంది ఫోన్లు చేశాం వెంటనే సహాయం కావాలి!",
    originalTranscript: "వరద నీరు ట్రాన్స్‌ఫార్మర్ దగ్గరకు వచ్చేసింది, 7 మంది ఫోన్లు చేశాం వెంటనే సహాయం కావాలి!",
    englishTranslation: "Stormwater inundation surrounding critical electrical junction. 7 corroborated citizen calls merged automatically within 85m radius.",
    finalCategory: "Water",
    issueCategory: "Water",
    hazardPriorityScore: 5,
    priorityScore: 5,
    summary: "Severe Substation Inundation & Storm Drain Rupture (7 Corroborated Reports Merged into Single Problem)",
    actionableSummary: "Severe Substation Inundation & Storm Drain Rupture (7 Corroborated Reports Merged into Single Problem)",
    recommendedDispatchUnit: "GHMC Rapid Inundation Squad & TSSPDCL Electrical Isolation Cell",
    estimatedRepairCostUSD: 2400,
    recommendedCrewSize: 6,
    status: "OPEN",
    resolutionQualityScore: 0,
    dispatchLogs: [
      { timestamp: "2026-08-19 14:33 UTC", note: "CYPHER Corroboration Engine merged 7 citizen signals (<100m Haversine) into 1 ticket.", officer: "Civic AI Core" }
    ],
    duplicateCount: 7,
    corroboratedReports: 7,
    corroborationDetails: [
      { citizen: "Ramesh Sharma", phone: "+91 98490 12345", time: "14:20 UTC", distanceM: 0, medium: "Voice Memo (Telugu)", transcript: "Water rising rapidly near substation foundation." },
      { citizen: "Ananya Rao", phone: "+91 98490 23456", time: "14:22 UTC", distanceM: 18, medium: "Photo + Text (English)", transcript: "Culvert breach flooding road, cars stranded." },
      { citizen: "Vikram Reddy", phone: "+91 98490 34567", time: "14:24 UTC", distanceM: 32, medium: "Voice Memo (Hindi)", transcript: "Bijli ke khambe ke paas paani bhar gaya hai, khatra hai." },
      { citizen: "Priya Sundaram", phone: "+91 98490 45678", time: "14:26 UTC", distanceM: 45, medium: "Photo Upload", transcript: "Transformer foundation submerged under 3.5ft water." },
      { citizen: "Syed Farooq", phone: "+91 98490 56789", time: "14:28 UTC", distanceM: 63, medium: "Voice Memo (Urdu)", transcript: "Gutter ka paani sadak pe beh raha hai, road blocked." },
      { citizen: "Kavita Nair", phone: "+91 98490 67890", time: "14:30 UTC", distanceM: 78, medium: "Text (English)", transcript: "Manhole cover popped off under excessive hydrostatic pressure." },
      { citizen: "Deepak Verma", phone: "+91 98490 78901", time: "14:31 UTC", distanceM: 84, medium: "Voice Memo (Hindi)", transcript: "Emergency de-watering pumps needed immediately." }
    ],
    livenessVerified: true,
    piiRedacted: true,
    hazard_category: "Water_Sewer",
    normalized_summary: "Severe Substation Inundation & Storm Drain Rupture (7 Corroborated Reports Merged into Single Problem)",
    distress_score: 0.94,
    criticality_level: 5,
    contradiction_detected: false,
    contradiction_reason: "None. All 7 acoustic and optical modalities corroborate deep inundation threatening power distribution.",
    recommended_crew: "Rapid Inundation & High-Voltage De-energization Unit",
    required_equipment: ["High-Capacity Submersible Trash Pumps", "Insulated Arc-Flash Suits", "Spillway Sandbag Barriers"],
    hitl_required: true,
    hitl_reason: "Level 5 Critical Life-Safety Risk detected with 7 corroborated citizen signals. Mandatory human authorization required before crew dispatch.",
    hitl_authorized: false,
    embedding: generateDeterministicSemanticVector("water storm flood 7 reports substation hyderabad"),
  },
  {
    id: "rep-000-contradiction",
    referenceId: "BRICS-IND-2026-7708",
    ticketId: "CYP-2026-7708",
    timestamp: "2026-08-19 14:40 UTC",
    createdAt: Date.now() - 1000 * 60 * 8,
    citizenName: "Aditya Verma",
    verifiedPhone: "+91 99887 66554",
    country: "India",
    language: "Hindi / English",
    documentType: "Aadhaar Card",
    problemDomain: "Power",
    location: "Madhapur Substation Boundary, Hyderabad",
    lat: 17.4485,
    lng: 78.3908,
    coordinates: { lat: 17.4485, lng: 78.3908 },
    typedComplaint: "Citizen acoustic memo reported 'just a tiny curb leak', but uploaded camera frame reveals violent water pipe rupture blasting directly into 11kV step-down transformer.",
    hasAudio: true,
    hasPhoto: true,
    preRepairPhotoUrl: "https://images.unsplash.com/photo-1584467735815-f778f274e296?w=800&auto=format&fit=crop&q=80",
    postRepairPhotoUrl: "https://images.unsplash.com/photo-1509391365360-2e959784a276?w=800&auto=format&fit=crop&q=80",
    transcription: "Sir chhota sa paani ka leak hai sadak ke kinare, koi badi baat nahi lagti.",
    originalTranscript: "Sir chhota sa paani ka leak hai sadak ke kinare, koi badi baat nahi lagti.",
    englishTranslation: "Sir, just a tiny water leak at the street edge, does not seem like a big deal.",
    finalCategory: "Power",
    issueCategory: "Power",
    hazardPriorityScore: 5,
    priorityScore: 5,
    summary: "Cross-Modal Contradiction: Voice reported 'minor leak', photo indicates 'transformer flooding'.",
    actionableSummary: "Cross-Modal Contradiction: Voice reported 'minor leak', photo indicates 'transformer flooding'.",
    recommendedDispatchUnit: "High-Voltage Electrical Response Team & Flood Barrier Squad",
    estimatedRepairCostUSD: 3100,
    recommendedCrewSize: 5,
    status: "OPEN",
    resolutionQualityScore: 0,
    dispatchLogs: [
      { timestamp: "2026-08-19 14:41 UTC", note: "Cross-modal contradiction detected between acoustic voice transcript and optical vision features.", officer: "Civic AI Core" }
    ],
    duplicateCount: 1,
    corroboratedReports: 1,
    livenessVerified: true,
    piiRedacted: true,
    hazard_category: "Electrical",
    normalized_summary: "CROSS-MODAL CONFLICT: Acoustic report claims minor curb drip, while high-resolution computer vision confirms 4.5ft deluge submerging 11kV live transformer.",
    distress_score: 0.88,
    criticality_level: 5,
    contradiction_detected: true,
    contradiction_reason: "Voice reported 'minor leak', photo indicates 'transformer flooding'.",
    recommended_crew: "High-Voltage Electrical Response Team & Flood Barrier Squad",
    required_equipment: ["Insulated Bucket Truck", "High-Voltage Voltage Detector", "Infrared Arc-Flash Camera"],
    hitl_required: true,
    hitl_reason: "Cross-Modal Contradiction Flagged: Voice reported 'minor leak', photo indicates 'transformer flooding'. Mandatory operator inspection required.",
    hitl_authorized: false,
    embedding: generateDeterministicSemanticVector("transformer leak flood contradiction water power"),
  },
  // --- HYDERABAD, INDIA ---
  {
    id: "rep-001",
    referenceId: "BRICS-IND-2026-8801",
    ticketId: "CYP-2026-8801",
    timestamp: "2026-08-19 14:15 UTC",
    createdAt: Date.now() - 1000 * 60 * 30,
    citizenName: "Venkatesh Rao",
    verifiedPhone: "+91 94401 23456",
    country: "India",
    language: "Telugu",
    documentType: "Voter ID Card",
    problemDomain: "Roads",
    location: "Main Market Road, Gachibowli, Hyderabad, Telangana",
    lat: 17.4401,
    lng: 78.3489,
    coordinates: { lat: 17.4401, lng: 78.3489 },
    typedComplaint: "రోడ్డు మధ్యలో పెద్ద గుంత ఏర్పడింది, బైక్ నడిపే వాళ్ళు కింద పడిపోతున్నారు. రాత్రి పూట కనిపించక ప్రమాదాలు జరుగుతున్నాయి.",
    hasAudio: true,
    hasPhoto: true,
    preRepairPhotoUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80",
    postRepairPhotoUrl: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&auto=format&fit=crop&q=80",
    transcription: "రోడ్డు మధ్యలో పెద్ద గుంత ఏర్పడింది, బైక్ నడిపే వాళ్ళు కింద పడిపోతున్నారు. రాత్రి పూట కనిపించక ప్రమాదాలు జరుగుతున్నాయి.",
    originalTranscript: "రోడ్డు మధ్యలో పెద్ద గుంత ఏర్పడింది, బైక్ నడిపే వాళ్ళు కింద పడిపోతున్నారు. రాత్రి పూట కనిపించక ప్రమాదాలు జరుగుతున్నాయి.",
    englishTranslation: "A deep crater pothole has formed in the middle of the road. Two-wheeler riders are falling down at night due to lack of street illumination.",
    finalCategory: "Roads",
    issueCategory: "Roads",
    hazardPriorityScore: 4,
    priorityScore: 4,
    summary: "High-risk roadway crater in active transit corridor causing two-wheeler accidents.",
    actionableSummary: "High-risk roadway crater in active transit corridor causing two-wheeler accidents.",
    recommendedDispatchUnit: "GHMC Road Maintenance & Bitumen Patch Squad 02",
    estimatedRepairCostUSD: 380,
    recommendedCrewSize: 3,
    status: "OPEN",
    resolutionQualityScore: 0,
    dispatchLogs: [
      { timestamp: "2026-08-19 14:18 UTC", note: "Automated AI Triage assigned Priority 4 (Severe Roadway Hazard).", officer: "Civic AI Core" }
    ],
    duplicateCount: 3,
    livenessVerified: true,
    piiRedacted: true,
    embedding: generateDeterministicSemanticVector("road pothole crater accident motorcycle hyderabad"),
  },
  {
    id: "rep-002",
    referenceId: "BRICS-IND-2026-8802",
    ticketId: "CYP-2026-8802",
    timestamp: "2026-08-19 13:45 UTC",
    createdAt: Date.now() - 1000 * 60 * 60,
    citizenName: "Pooja Reddy",
    verifiedPhone: "+91 98850 78901",
    country: "India",
    language: "Telugu",
    documentType: "Aadhaar Card",
    problemDomain: "Water",
    location: "Cyber Towers Junction, Hitec City, Hyderabad, Telangana",
    lat: 17.4435,
    lng: 78.3772,
    coordinates: { lat: 17.4435, lng: 78.3772 },
    typedComplaint: "హైటెక్ సిటీ ప్రధాన పైపులైన్ పగిలి మంచి నీరంతా రోడ్డుపై వృథాగా పోతోంది.",
    hasAudio: true,
    hasPhoto: true,
    preRepairPhotoUrl: "https://images.unsplash.com/photo-1584467735815-f778f274e296?w=600&auto=format&fit=crop&q=80",
    postRepairPhotoUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&auto=format&fit=crop&q=80",
    transcription: "హైటెక్ సిటీ ప్రధాన పైపులైన్ పగిలి మంచి నీరంతా రోడ్డుపై వృథాగా పోతోంది.",
    originalTranscript: "హైటెక్ సిటీ ప్రధాన పైపులైన్ పగిలి మంచి నీరంతా రోడ్డుపై వృథాగా పోతోంది.",
    englishTranslation: "Major potable water pipeline fractured near Cyber Towers, clean drinking water gushing onto the carriageway.",
    finalCategory: "Water",
    issueCategory: "Water",
    hazardPriorityScore: 3,
    priorityScore: 3,
    summary: "Potable distribution pipeline fracture causing street waterlogging and supply drop.",
    actionableSummary: "Potable distribution pipeline fracture causing street waterlogging and supply drop.",
    recommendedDispatchUnit: "HMWSSB Water Supply Rapid Repair Cell",
    estimatedRepairCostUSD: 450,
    recommendedCrewSize: 3,
    status: "IN_PROGRESS",
    resolutionQualityScore: 60,
    dispatchLogs: [
      { timestamp: "2026-08-19 13:50 UTC", note: "HMWSSB excavation team dispatched to isolate feeder valve.", officer: "Dispatcher K. Rao" }
    ],
    duplicateCount: 2,
    livenessVerified: true,
    piiRedacted: true,
    embedding: generateDeterministicSemanticVector("water pipeline fractured leak gushing hyderabad"),
  },
  {
    id: "rep-003",
    referenceId: "BRICS-IND-2026-8803",
    ticketId: "CYP-2026-8803",
    timestamp: "2026-08-19 12:20 UTC",
    createdAt: Date.now() - 1000 * 60 * 140,
    citizenName: "Mohammed Imran",
    verifiedPhone: "+91 97001 54321",
    country: "India",
    language: "Telugu",
    documentType: "Driving License",
    problemDomain: "Power",
    location: "Charminar Heritage Plaza, Old City, Hyderabad, Telangana",
    lat: 17.3616,
    lng: 78.4747,
    coordinates: { lat: 17.3616, lng: 78.4747 },
    typedComplaint: "చార్మినార్ దగ్గర 11kV ట్రాన్స్‌ఫార్మర్ పేలి మంటలు చెలరేగాయి, వెంటనే పవర్ ఆపాలి.",
    hasAudio: true,
    hasPhoto: true,
    preRepairPhotoUrl: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=600&auto=format&fit=crop&q=80",
    postRepairPhotoUrl: "https://images.unsplash.com/photo-1509391365360-2e959784a276?w=600&auto=format&fit=crop&q=80",
    transcription: "చార్మినార్ దగ్గర 11kV ట్రాన్స్‌ఫార్మర్ పేలి మంటలు చెలరేగాయి, వెంటనే పవర్ ఆపాలి.",
    originalTranscript: "చార్మినార్ దగ్గర 11kV ట్రాన్స్‌ఫార్మర్ పేలి మంటలు చెలరేగాయి, వెంటనే పవర్ ఆపాలి.",
    englishTranslation: "11kV distribution transformer exploded near Charminar heritage precinct, active arcing and sparks threatening pedestrians.",
    finalCategory: "Power",
    issueCategory: "Power",
    hazardPriorityScore: 5,
    priorityScore: 5,
    summary: "CRITICAL: Exploded 11kV transformer with active sparks and crowd hazard in heritage tourist area.",
    actionableSummary: "CRITICAL: Exploded 11kV transformer with active sparks and crowd hazard in heritage tourist area.",
    recommendedDispatchUnit: "TSSPDCL High-Voltage Emergency Rapid Squad & Fire Services",
    estimatedRepairCostUSD: 1200,
    recommendedCrewSize: 5,
    status: "OPEN",
    resolutionQualityScore: 0,
    dispatchLogs: [
      { timestamp: "2026-08-19 12:22 UTC", note: "Level 5 Life Emergency alert triggered. Feeder trip signal sent.", officer: "Civic AI Core" }
    ],
    duplicateCount: 5,
    livenessVerified: true,
    piiRedacted: true,
    embedding: generateDeterministicSemanticVector("transformer exploded fire power sparks charminar"),
  },

  // --- SÃO PAULO, BRAZIL ---
  {
    id: "rep-004",
    referenceId: "BRICS-BRA-2026-8804",
    ticketId: "CYP-2026-8804",
    timestamp: "2026-08-19 14:00 UTC",
    createdAt: Date.now() - 1000 * 60 * 45,
    citizenName: "Mateo Silva Santos",
    verifiedPhone: "+55 11 98123-4567",
    country: "Brazil",
    language: "Portuguese",
    documentType: "RG - Registro Geral",
    problemDomain: "Roads",
    location: "Avenida Paulista 1578, Bela Vista, São Paulo",
    lat: -23.5615,
    lng: -46.6560,
    coordinates: { lat: -23.5615, lng: -46.6560 },
    typedComplaint: "Cratera profunda se abriu na faixa exclusiva de ônibus da Avenida Paulista, causando lentidão extrema.",
    hasAudio: true,
    hasPhoto: true,
    preRepairPhotoUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80",
    postRepairPhotoUrl: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&auto=format&fit=crop&q=80",
    transcription: "Cratera profunda se abriu na faixa exclusiva de ônibus da Avenida Paulista, causando lentidão extrema.",
    originalTranscript: "Cratera profunda se abriu na faixa exclusiva de ônibus da Avenida Paulista, causando lentidão extrema.",
    englishTranslation: "Deep asphalt crater opened in the dedicated bus lane on Paulista Avenue, disrupting transit corridor flow.",
    finalCategory: "Roads",
    issueCategory: "Roads",
    hazardPriorityScore: 3,
    priorityScore: 3,
    summary: "Asphalt subsidence crater in central BRT corridor on Avenida Paulista.",
    actionableSummary: "Asphalt subsidence crater in central BRT corridor on Avenida Paulista.",
    recommendedDispatchUnit: "CET SP & Pavimentação Urbana Regional Sé",
    estimatedRepairCostUSD: 520,
    recommendedCrewSize: 3,
    status: "IN_PROGRESS",
    resolutionQualityScore: 78,
    dispatchLogs: [
      { timestamp: "2026-08-19 14:05 UTC", note: "CET transit diversion deployed around sinkhole.", officer: "Operador CET 12" }
    ],
    duplicateCount: 2,
    livenessVerified: true,
    piiRedacted: true,
    embedding: generateDeterministicSemanticVector("cratera avenida paulista onibus sao paulo transito"),
  },
  {
    id: "rep-005",
    referenceId: "BRICS-BRA-2026-8805",
    ticketId: "CYP-2026-8805",
    timestamp: "2026-08-19 13:10 UTC",
    createdAt: Date.now() - 1000 * 60 * 95,
    citizenName: "Camila Guimarães",
    verifiedPhone: "+55 11 99234-5678",
    country: "Brazil",
    language: "Portuguese",
    documentType: "CNH - Carteira Nacional de Habilitação",
    problemDomain: "Water",
    location: "Rua dos Pinheiros 800, Pinheiros, São Paulo",
    lat: -23.5670,
    lng: -46.6934,
    coordinates: { lat: -23.5670, lng: -46.6934 },
    typedComplaint: "Rompimento de adutora mestre da Sabesp inundando garagens subterrâneas e calçadas em Pinheiros.",
    hasAudio: true,
    hasPhoto: true,
    preRepairPhotoUrl: "https://images.unsplash.com/photo-1584467735815-f778f274e296?w=600&auto=format&fit=crop&q=80",
    postRepairPhotoUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&auto=format&fit=crop&q=80",
    transcription: "Rompimento de adutora mestre da Sabesp inundando garagens subterrâneas e calçadas em Pinheiros.",
    originalTranscript: "Rompimento de adutora mestre da Sabesp inundando garagens subterrâneas e calçadas em Pinheiros.",
    englishTranslation: "Master distribution water trunk burst flooding underground basements and pedestrian sidewalks in Pinheiros.",
    finalCategory: "Water",
    issueCategory: "Water",
    hazardPriorityScore: 4,
    priorityScore: 4,
    summary: "High-pressure Sabesp water trunk rupture causing structural basement flooding.",
    actionableSummary: "High-pressure Sabesp water trunk rupture causing structural basement flooding.",
    recommendedDispatchUnit: "SABESP Emergência Hidráulica & Defesa Civil SP",
    estimatedRepairCostUSD: 890,
    recommendedCrewSize: 4,
    status: "OPEN",
    resolutionQualityScore: 0,
    dispatchLogs: [
      { timestamp: "2026-08-19 13:15 UTC", note: "Emergency valve isolation requested to Sabesp control center.", officer: "Civic AI Core" }
    ],
    duplicateCount: 4,
    livenessVerified: true,
    piiRedacted: true,
    embedding: generateDeterministicSemanticVector("rompimento adutora sabesp inundacao pinheiros agua"),
  },
  {
    id: "rep-006",
    referenceId: "BRICS-BRA-2026-8806",
    ticketId: "CYP-2026-8806",
    timestamp: "2026-08-19 10:00 UTC",
    createdAt: Date.now() - 1000 * 60 * 280,
    citizenName: "Felipe Rodrigues",
    verifiedPhone: "+55 11 97345-6789",
    country: "Brazil",
    language: "Portuguese",
    documentType: "RG - Registro Geral",
    problemDomain: "Infrastructure",
    location: "Viaduto Alcântara Machado, Mooca, São Paulo",
    lat: -23.5558,
    lng: -46.5980,
    coordinates: { lat: -23.5558, lng: -46.5980 },
    typedComplaint: "Guarda-corpo da passarela de pedestres foi consertado e pintado pela equipe municipal.",
    hasAudio: false,
    hasPhoto: true,
    preRepairPhotoUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?w=600&auto=format&fit=crop&q=80",
    postRepairPhotoUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&auto=format&fit=crop&q=80",
    transcription: "Guarda-corpo da passarela de pedestres foi consertado e pintado pela equipe municipal.",
    originalTranscript: "Guarda-corpo da passarela de pedestres foi consertado e pintado pela equipe municipal.",
    englishTranslation: "Pedestrian overpass safety railing has been reinforced, re-welded, and coated by municipal crews.",
    finalCategory: "Infrastructure",
    issueCategory: "Infrastructure",
    hazardPriorityScore: 2,
    priorityScore: 2,
    summary: "Safety guardrail restored and protective barrier installed on Mooca viaduct.",
    actionableSummary: "Safety guardrail restored and protective barrier installed on Mooca viaduct.",
    recommendedDispatchUnit: "SIURB Secretaria de Infraestrutura Urbana",
    estimatedRepairCostUSD: 240,
    recommendedCrewSize: 2,
    status: "RESOLVED",
    resolutionQualityScore: 96,
    dispatchLogs: [
      { timestamp: "2026-08-19 11:30 UTC", note: "Final repair inspection confirmed: 96% quality score.", officer: "Fiscal SIURB" }
    ],
    duplicateCount: 1,
    livenessVerified: true,
    piiRedacted: true,
    embedding: generateDeterministicSemanticVector("passarela viaduto mooca guarda corpo reparo resolvido"),
  },

  // --- JOHANNESBURG, SOUTH AFRICA ---
  {
    id: "rep-007",
    referenceId: "BRICS-ZAF-2026-8807",
    ticketId: "CYP-2026-8807",
    timestamp: "2026-08-19 14:10 UTC",
    createdAt: Date.now() - 1000 * 60 * 35,
    citizenName: "Thabo Molefe",
    verifiedPhone: "+27 82 345 6789",
    country: "South Africa",
    language: "Zulu",
    documentType: "Smart National Identity Card",
    problemDomain: "Infrastructure",
    location: "M1 Highway Double-Decker Overpass, Newtown, Johannesburg",
    lat: -26.2041,
    lng: 28.0473,
    coordinates: { lat: -26.2041, lng: 28.0473 },
    typedComplaint: "Ukuqhekeka okukhulu kukhonkolo lwebhuloho lomgwaqo omkhulu we-M1, izingcezu ziwela ezimotweni.",
    hasAudio: true,
    hasPhoto: true,
    preRepairPhotoUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?w=600&auto=format&fit=crop&q=80",
    postRepairPhotoUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&auto=format&fit=crop&q=80",
    transcription: "Ukuqhekeka okukhulu kukhonkolo lwebhuloho lomgwaqo omkhulu we-M1, izingcezu ziwela ezimotweni.",
    originalTranscript: "Ukuqhekeka okukhulu kukhonkolo lwebhuloho lomgwaqo omkhulu we-M1, izingcezu ziwela ezimotweni.",
    englishTranslation: "Severe structural concrete spalling and beam shear crack on M1 highway deck; concrete chunks falling onto traffic below.",
    finalCategory: "Infrastructure",
    issueCategory: "Infrastructure",
    hazardPriorityScore: 5,
    priorityScore: 5,
    summary: "CRITICAL: Elevated freeway structural delamination dropping concrete onto active highway lanes.",
    actionableSummary: "CRITICAL: Elevated freeway structural delamination dropping concrete onto active highway lanes.",
    recommendedDispatchUnit: "JRA (Johannesburg Roads Agency) Structural Emergency Task Force & JMPD",
    estimatedRepairCostUSD: 2400,
    recommendedCrewSize: 6,
    status: "OPEN",
    resolutionQualityScore: 0,
    dispatchLogs: [
      { timestamp: "2026-08-19 14:12 UTC", note: "Emergency lane closure ordered by JMPD traffic control.", officer: "Civic AI Core" }
    ],
    duplicateCount: 6,
    livenessVerified: true,
    piiRedacted: true,
    embedding: generateDeterministicSemanticVector("bridge concrete crack falling debris m1 highway johannesburg"),
  },
  {
    id: "rep-008",
    referenceId: "BRICS-ZAF-2026-8808",
    ticketId: "CYP-2026-8808",
    timestamp: "2026-08-19 12:50 UTC",
    createdAt: Date.now() - 1000 * 60 * 115,
    citizenName: "Lerato Dlamini",
    verifiedPhone: "+27 83 456 7890",
    country: "South Africa",
    language: "Zulu",
    documentType: "Smart National Identity Card",
    problemDomain: "Power",
    location: "Sandton Central Business District, Johannesburg",
    lat: -26.1076,
    lng: 28.0567,
    coordinates: { lat: -26.1076, lng: 28.0567 },
    typedComplaint: "Substation feeder cable theft caused total blackout across three business blocks. Traffic lights dead.",
    hasAudio: true,
    hasPhoto: true,
    preRepairPhotoUrl: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=600&auto=format&fit=crop&q=80",
    postRepairPhotoUrl: "https://images.unsplash.com/photo-1509391365360-2e959784a276?w=600&auto=format&fit=crop&q=80",
    transcription: "Substation feeder cable theft caused total blackout across three business blocks. Traffic lights dead.",
    originalTranscript: "Substation feeder cable theft caused total blackout across three business blocks. Traffic lights dead.",
    englishTranslation: "Municipal substation feeder cable vandalism caused total power outage across three commercial blocks, traffic lights offline.",
    finalCategory: "Power",
    issueCategory: "Power",
    hazardPriorityScore: 3,
    priorityScore: 3,
    summary: "Substation feeder vandalism causing blackout and critical signal intersection failure.",
    actionableSummary: "Substation feeder vandalism causing blackout and critical signal intersection failure.",
    recommendedDispatchUnit: "City Power Johannesburg Heavy Cables Emergency Unit",
    estimatedRepairCostUSD: 1100,
    recommendedCrewSize: 4,
    status: "IN_PROGRESS",
    resolutionQualityScore: 72,
    dispatchLogs: [
      { timestamp: "2026-08-19 13:00 UTC", note: "Cable re-routing crew on site; generator backup online for traffic lights.", officer: "City Power Dispatch" }
    ],
    duplicateCount: 3,
    livenessVerified: true,
    piiRedacted: true,
    embedding: generateDeterministicSemanticVector("city power cable blackout sandton traffic lights"),
  },
  {
    id: "rep-009",
    referenceId: "BRICS-ZAF-2026-8809",
    ticketId: "CYP-2026-8809",
    timestamp: "2026-08-19 09:15 UTC",
    createdAt: Date.now() - 1000 * 60 * 330,
    citizenName: "Mandla Khumalo",
    verifiedPhone: "+27 84 567 8901",
    country: "South Africa",
    language: "Zulu",
    documentType: "National Passport",
    problemDomain: "Water",
    location: "Vilakazi Street, Orlando West, Soweto, Johannesburg",
    lat: -26.2485,
    lng: 27.8540,
    coordinates: { lat: -26.2485, lng: 27.8540 },
    typedComplaint: "Ipayipi lamanzi elalivuza e-Vilakazi Street selilungisiwe ngokuphelele.",
    hasAudio: false,
    hasPhoto: true,
    preRepairPhotoUrl: "https://images.unsplash.com/photo-1584467735815-f778f274e296?w=600&auto=format&fit=crop&q=80",
    postRepairPhotoUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&auto=format&fit=crop&q=80",
    transcription: "Ipayipi lamanzi elalivuza e-Vilakazi Street selilungisiwe ngokuphelele.",
    originalTranscript: "Ipayipi lamanzi elalivuza e-Vilakazi Street selilungisiwe ngokuphelele.",
    englishTranslation: "Leaking municipal water connection on Vilakazi Street has been successfully excavated, re-sleeved, and backfilled.",
    finalCategory: "Water",
    issueCategory: "Water",
    hazardPriorityScore: 1,
    priorityScore: 1,
    summary: "Heritage tourist street water service line restored and paved.",
    actionableSummary: "Heritage tourist street water service line restored and paved.",
    recommendedDispatchUnit: "Johannesburg Water Depot 07",
    estimatedRepairCostUSD: 180,
    recommendedCrewSize: 2,
    status: "RESOLVED",
    resolutionQualityScore: 94,
    dispatchLogs: [
      { timestamp: "2026-08-19 11:45 UTC", note: "Resolution verified by municipal water quality audit: 94%.", officer: "Inspector N. Buthelezi" }
    ],
    duplicateCount: 1,
    livenessVerified: true,
    piiRedacted: true,
    embedding: generateDeterministicSemanticVector("water pipe leak vilakazi soweto resolved"),
  },

  // --- BEIJING, CHINA ---
  {
    id: "rep-010",
    referenceId: "BRICS-CHN-2026-8810",
    ticketId: "CYP-2026-8810",
    timestamp: "2026-08-19 13:55 UTC",
    createdAt: Date.now() - 1000 * 60 * 50,
    citizenName: "Chen Wei",
    verifiedPhone: "+86 138 0013 8000",
    country: "China",
    language: "Chinese",
    documentType: "Resident Identity Card",
    problemDomain: "Power",
    location: "Jianguomen Outer Street, Chaoyang CBD, Beijing",
    lat: 39.9150,
    lng: 116.4600,
    coordinates: { lat: 39.9150, lng: 116.4600 },
    typedComplaint: "朝阳区建国门外大街地下高压电缆井冒烟，并伴有剧烈刺鼻焦糊味。",
    hasAudio: true,
    hasPhoto: true,
    preRepairPhotoUrl: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=600&auto=format&fit=crop&q=80",
    postRepairPhotoUrl: "https://images.unsplash.com/photo-1509391365360-2e959784a276?w=600&auto=format&fit=crop&q=80",
    transcription: "朝阳区建国门外大街地下高压电缆井冒烟，并伴有剧烈刺鼻焦糊味。",
    originalTranscript: "朝阳区建国门外大街地下高压电缆井冒烟，并伴有剧烈刺鼻焦糊味。",
    englishTranslation: "Subsurface underground high-voltage utility conduit smoking heavily with intense electrical burning odor in Chaoyang CBD.",
    finalCategory: "Power",
    issueCategory: "Power",
    hazardPriorityScore: 4,
    priorityScore: 4,
    summary: "High-voltage underground electrical duct smoking with thermal runaway danger.",
    actionableSummary: "High-voltage underground electrical duct smoking with thermal runaway danger.",
    recommendedDispatchUnit: "State Grid Beijing Electric Power Emergency Response Unit",
    estimatedRepairCostUSD: 950,
    recommendedCrewSize: 4,
    status: "OPEN",
    resolutionQualityScore: 0,
    dispatchLogs: [
      { timestamp: "2026-08-19 13:58 UTC", note: "Thermal camera survey scheduled; grid switchgear safety lock engaged.", officer: "Civic AI Core" }
    ],
    duplicateCount: 3,
    livenessVerified: true,
    piiRedacted: true,
    embedding: generateDeterministicSemanticVector("underground cable smoking fire chaoyang beijing power"),
  },
  {
    id: "rep-011",
    referenceId: "BRICS-CHN-2026-8811",
    ticketId: "CYP-2026-8811",
    timestamp: "2026-08-19 11:20 UTC",
    createdAt: Date.now() - 1000 * 60 * 205,
    citizenName: "Lin Xiaofeng",
    verifiedPhone: "+86 139 1234 5678",
    country: "China",
    language: "Chinese",
    documentType: "Resident Identity Card",
    problemDomain: "Roads",
    location: "Zhongguancun South Street, Haidian District, Beijing",
    lat: 39.9800,
    lng: 116.3100,
    coordinates: { lat: 39.9800, lng: 116.3100 },
    typedComplaint: "中关村南大街路面沉降约15公分，影响早晚高峰自动驾驶和公交车平稳通行。",
    hasAudio: true,
    hasPhoto: true,
    preRepairPhotoUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80",
    postRepairPhotoUrl: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&auto=format&fit=crop&q=80",
    transcription: "中关村南大街路面沉降约15公分，影响早晚高峰自动驾驶和公交车平稳通行。",
    originalTranscript: "中关村南大街路面沉降约15公分，影响早晚高峰自动驾驶和公交车平稳通行。",
    englishTranslation: "Roadway subsidence of approximately 15cm detected along Zhongguancun South Street, disrupting morning transit stability.",
    finalCategory: "Roads",
    issueCategory: "Roads",
    hazardPriorityScore: 3,
    priorityScore: 3,
    summary: "Asphalt subsidence depression affecting autonomous and public transit corridor.",
    actionableSummary: "Asphalt subsidence depression affecting autonomous and public transit corridor.",
    recommendedDispatchUnit: "Beijing Municipal Road Maintenance Engineering Bureau Team 4",
    estimatedRepairCostUSD: 600,
    recommendedCrewSize: 3,
    status: "IN_PROGRESS",
    resolutionQualityScore: 80,
    dispatchLogs: [
      { timestamp: "2026-08-19 12:00 UTC", note: "Ground penetrating radar completed; asphalt milling underway.", officer: "Engineer Zhang" }
    ],
    duplicateCount: 2,
    livenessVerified: true,
    piiRedacted: true,
    embedding: generateDeterministicSemanticVector("zhongguancun road subsidence haidian beijing asphalt"),
  },
  {
    id: "rep-012",
    referenceId: "BRICS-CHN-2026-8812",
    ticketId: "CYP-2026-8812",
    timestamp: "2026-08-19 08:30 UTC",
    createdAt: Date.now() - 1000 * 60 * 375,
    citizenName: "Wang Fang",
    verifiedPhone: "+86 136 7890 1234",
    country: "China",
    language: "Chinese",
    documentType: "Resident Identity Card",
    problemDomain: "Infrastructure",
    location: "Wangfujing Pedestrian Commercial Avenue, Dongcheng, Beijing",
    lat: 39.9280,
    lng: 116.4170,
    coordinates: { lat: 39.9280, lng: 116.4170 },
    typedComplaint: "王府井步行街仿古花岗岩地砖脱落松动问题已由市政工程局连夜修缮平整。",
    hasAudio: false,
    hasPhoto: true,
    preRepairPhotoUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?w=600&auto=format&fit=crop&q=80",
    postRepairPhotoUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&auto=format&fit=crop&q=80",
    transcription: "王府井步行街仿古花岗岩地砖脱落松动问题已由市政工程局连夜修缮平整。",
    originalTranscript: "王府井步行街仿古花岗岩地砖脱落松动问题已由市政工程局连夜修缮平整。",
    englishTranslation: "Loose historical granite pavers in Wangfujing pedestrian avenue have been leveled and re-grouted by municipal repair crews.",
    finalCategory: "Infrastructure",
    issueCategory: "Infrastructure",
    hazardPriorityScore: 2,
    priorityScore: 2,
    summary: "Pedestrian promenade paving restored with anti-slip polymer mortar.",
    actionableSummary: "Pedestrian promenade paving restored with anti-slip polymer mortar.",
    recommendedDispatchUnit: "Dongcheng District Municipal Landscape & Pavement Office",
    estimatedRepairCostUSD: 190,
    recommendedCrewSize: 2,
    status: "RESOLVED",
    resolutionQualityScore: 98,
    dispatchLogs: [
      { timestamp: "2026-08-19 10:15 UTC", note: "Overnight paving verified with high-precision laser level: 98%.", officer: "Supervisor Liu" }
    ],
    duplicateCount: 1,
    livenessVerified: true,
    piiRedacted: true,
    embedding: generateDeterministicSemanticVector("wangfujing paving granite stones repaired resolved beijing"),
  },

  // --- MOSCOW, RUSSIA ---
  {
    id: "rep-013",
    referenceId: "BRICS-RUS-2026-8813",
    ticketId: "CYP-2026-8813",
    timestamp: "2026-08-19 14:12 UTC",
    createdAt: Date.now() - 1000 * 60 * 33,
    citizenName: "Dmitry Morozov",
    verifiedPhone: "+7 916 123-45-67",
    country: "Russia",
    language: "Russian",
    documentType: "Internal Passport of Russian Federation",
    problemDomain: "Water",
    location: "Tverskaya Street 14, Central Administrative Okrug, Moscow",
    lat: 55.7602,
    lng: 37.6058,
    coordinates: { lat: 55.7602, lng: 37.6058 },
    typedComplaint: "Прорыв магистральной теплотрассы на Тверской. Кипяток под давлением заливает тротуар, нулевая видимость из-за пара!",
    hasAudio: true,
    hasPhoto: true,
    preRepairPhotoUrl: "https://images.unsplash.com/photo-1584467735815-f778f274e296?w=600&auto=format&fit=crop&q=80",
    postRepairPhotoUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&auto=format&fit=crop&q=80",
    transcription: "Прорыв магистральной теплотрассы на Тверской. Кипяток под давлением заливает тротуар, нулевая видимость из-за пара!",
    originalTranscript: "Прорыв магистральной теплотрассы на Тверской. Кипяток под давлением заливает тротуар, нулевая видимость из-за пара!",
    englishTranslation: "Rupture of central high-pressure district steam/heating main on Tverskaya. Scalding water flooding walkway with zero visibility.",
    finalCategory: "Water",
    issueCategory: "Water",
    hazardPriorityScore: 5,
    priorityScore: 5,
    summary: "CRITICAL: Scalding district heating line failure with zero visibility and burn risk on main avenue.",
    actionableSummary: "CRITICAL: Scalding district heating line failure with zero visibility and burn risk on main avenue.",
    recommendedDispatchUnit: "MOEK Emergency Thermal Brigade & EMERCOM Rescue Squadron",
    estimatedRepairCostUSD: 1800,
    recommendedCrewSize: 5,
    status: "OPEN",
    resolutionQualityScore: 0,
    dispatchLogs: [
      { timestamp: "2026-08-19 14:14 UTC", note: "Priority 5 alert dispatched: Thermal pipe shutoff valves activated.", officer: "Civic AI Core" }
    ],
    duplicateCount: 5,
    livenessVerified: true,
    piiRedacted: true,
    embedding: generateDeterministicSemanticVector("district heating main burst boiling steam tverskaya moscow"),
  },
  {
    id: "rep-014",
    referenceId: "BRICS-RUS-2026-8814",
    ticketId: "CYP-2026-8814",
    timestamp: "2026-08-19 12:40 UTC",
    createdAt: Date.now() - 1000 * 60 * 125,
    citizenName: "Elena Vasileva",
    verifiedPhone: "+7 926 234-56-78",
    country: "Russia",
    language: "Russian",
    documentType: "Internal Passport of Russian Federation",
    problemDomain: "Power",
    location: "Old Arbat Street 28, Arbat District, Moscow",
    lat: 55.7522,
    lng: 37.5925,
    coordinates: { lat: 55.7522, lng: 37.5925 },
    typedComplaint: "Повреждение кабельной муфты уличного освещения на Арбате, мерцают и гаснут фонари.",
    hasAudio: true,
    hasPhoto: true,
    preRepairPhotoUrl: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=600&auto=format&fit=crop&q=80",
    postRepairPhotoUrl: "https://images.unsplash.com/photo-1509391365360-2e959784a276?w=600&auto=format&fit=crop&q=80",
    transcription: "Повреждение кабельной муфты уличного освещения на Арбате, мерцают и гаснут фонари.",
    originalTranscript: "Повреждение кабельной муфты уличного освещения на Арбате, мерцают и гаснут фонари.",
    englishTranslation: "Faulty street lighting cable termination block on Arbat, erratic voltage fluctuations and dark pedestrian corridors.",
    finalCategory: "Power",
    issueCategory: "Power",
    hazardPriorityScore: 3,
    priorityScore: 3,
    summary: "Street lighting distribution box short circuit causing blackout along historic pedestrian promenade.",
    actionableSummary: "Street lighting distribution box short circuit causing blackout along historic pedestrian promenade.",
    recommendedDispatchUnit: "Mosgorsvet Underground Cable Repair Unit",
    estimatedRepairCostUSD: 410,
    recommendedCrewSize: 3,
    status: "IN_PROGRESS",
    resolutionQualityScore: 65,
    dispatchLogs: [
      { timestamp: "2026-08-19 13:00 UTC", note: "Mosgorsvet technician replacing damaged junction box sleeve.", officer: "Dispatcher S. Smirnov" }
    ],
    duplicateCount: 2,
    livenessVerified: true,
    piiRedacted: true,
    embedding: generateDeterministicSemanticVector("street light cable damaged arbat moscow power"),
  },
  {
    id: "rep-015",
    referenceId: "BRICS-RUS-2026-8815",
    ticketId: "CYP-2026-8815",
    timestamp: "2026-08-19 09:50 UTC",
    createdAt: Date.now() - 1000 * 60 * 295,
    citizenName: "Sergei Kuznetsov",
    verifiedPhone: "+7 903 345-67-89",
    country: "Russia",
    language: "Russian",
    documentType: "Internal Passport of Russian Federation",
    problemDomain: "Roads",
    location: "Krasnopresnenskaya Embankment, Presnensky District, Moscow",
    lat: 55.7558,
    lng: 37.5750,
    coordinates: { lat: 55.7558, lng: 37.5750 },
    typedComplaint: "Асфальтовое покрытие после зимнего пучения полностью восстановлено и укатано дорожными катками.",
    hasAudio: false,
    hasPhoto: true,
    preRepairPhotoUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80",
    postRepairPhotoUrl: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&auto=format&fit=crop&q=80",
    transcription: "Асфальтовое покрытие после зимнего пучения полностью восстановлено и укатано дорожными катками.",
    originalTranscript: "Асфальтовое покрытие после зимнего пучения полностью восстановлено и укатано дорожными катками.",
    englishTranslation: "Frost heave asphalt distress has been milled, fresh hot-mix bitumen paved and compacted.",
    finalCategory: "Roads",
    issueCategory: "Roads",
    hazardPriorityScore: 1,
    priorityScore: 1,
    summary: "Road surface restored with modern mastic asphalt overlay.",
    actionableSummary: "Road surface restored with modern mastic asphalt overlay.",
    recommendedDispatchUnit: "GBU Avtomobilnye Dorogi Presnya Division",
    estimatedRepairCostUSD: 310,
    recommendedCrewSize: 3,
    status: "RESOLVED",
    resolutionQualityScore: 95,
    dispatchLogs: [
      { timestamp: "2026-08-19 11:15 UTC", note: "Road surface quality scanned with high compliance score: 95%.", officer: "Engineer V. Popov" }
    ],
    duplicateCount: 1,
    livenessVerified: true,
    piiRedacted: true,
    embedding: generateDeterministicSemanticVector("asphalt road repair frost heave moscow presnya resolved"),
  },
];
